# Generated by Django 6.0.2 on 2026-02-13 01:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Casinos', '0003_alter_casino_creado_en_alter_casino_creado_por_and_more'),
        ('Usuarios', '0003_alter_usuarios_apellido_materno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría')),
                ('titulo', models.CharField(help_text='Descripción breve de la actividad extraordinaria', max_length=150, verbose_name='Título de la Tarea')),
                ('descripcion', models.TextField(help_text='Detalles técnicos o requerimientos de gerencia', verbose_name='Descripción de la Tarea')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica / Inmediata')], default='media', help_text='Nivel de importancia de la actividad', max_length=20, verbose_name='Prioridad de Tarea')),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('completada', 'Terminada'), ('cancelada', 'Cancelada')], default='pendiente', help_text='Estatus actual de la tarea especial', max_length=20, verbose_name='Estado de Avance')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento exacto en que se inició la tarea', verbose_name='Fecha de Apertura')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, help_text='Momento en que la tarea cambió a Terminada', null=True, verbose_name='Fecha de Finalización')),
                ('resultado_final', models.TextField(blank=True, help_text='Observaciones sobre cómo quedó el equipo o infraestructura', null=True, verbose_name='Resultado Final')),
                ('asignado_a', models.ForeignKey(blank=True, help_text='Técnico que se auto-asigna para realizar la labor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_ejecutadas', to='Usuarios.usuarios', verbose_name='Técnico Responsable')),
                ('casino', models.ForeignKey(help_text='Ubicación donde se debe realizar la tarea', on_delete=django.db.models.deletion.CASCADE, related_name='tareas_especiales', to='Casinos.casino', verbose_name='Casino / Sucursal')),
                ('creado_por_usuario', models.ForeignKey(help_text='Persona que registra la tarea en el sistema', on_delete=django.db.models.deletion.PROTECT, related_name='tareas_creadas', to='Usuarios.usuarios', verbose_name='Usuario que dio de Alta')),
            ],
            options={
                'verbose_name': 'Tarea Especial',
                'verbose_name_plural': 'Tareas Especiales',
                'db_table': 'tareas_especiales',
            },
        ),
    ]
