# Generated by Django 6.0.2 on 2026-02-12 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Casinos', '0002_casino_encargado_alter_casino_ciudad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, null=True, verbose_name='Notas de Auditoría')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Proveedor')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('email_corporativo', models.EmailField(max_length=254, verbose_name='Email Corporativo')),
                ('telefono_soporte', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Soporte')),
                ('email_soporte', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Soporte')),
                ('nombre_contacto_tecnico', models.CharField(blank=True, max_length=150, null=True, verbose_name='Contacto Técnico')),
                ('username', models.CharField(max_length=50, verbose_name='Usuario de Acceso')),
                ('password', models.CharField(max_length=100, verbose_name='Contraseña (Texto Plano)')),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_locales', to='Casinos.casino')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'unique_together': {('casino', 'nombre'), ('casino', 'username')},
            },
        ),
    ]
