# Generated by Django 6.0.2 on 2026-02-12 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casinos', '0003_alter_casino_creado_en_alter_casino_creado_por_and_more'),
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='casino',
            field=models.ForeignKey(help_text='Casino al que pertenece este proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_locales', to='Casinos.casino'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='creado_por',
            field=models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email_corporativo',
            field=models.EmailField(help_text='Correo electrónico principal de contacto', max_length=254, verbose_name='Email Corporativo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email_soporte',
            field=models.EmailField(blank=True, help_text='Correo del departamento de soporte técnico', max_length=254, null=True, verbose_name='Email de Soporte'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='esta_activo',
            field=models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='modificado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='modificado_por',
            field=models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(help_text='Razón social o nombre comercial del proveedor', max_length=150, verbose_name='Nombre del Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_contacto_tecnico',
            field=models.CharField(blank=True, help_text='Nombre del técnico o responsable asignado', max_length=150, null=True, verbose_name='Contacto Técnico'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='notas_internas',
            field=models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='password',
            field=models.CharField(help_text='Contraseña de acceso (almacenada sin cifrado)', max_length=100, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(help_text='Registro Federal de Contribuyentes', max_length=13, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_soporte',
            field=models.CharField(blank=True, help_text='Línea directa de soporte técnico', max_length=20, null=True, verbose_name='Teléfono Soporte'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='username',
            field=models.CharField(help_text='Nombre de usuario para acceder al sistema del proveedor', max_length=50, verbose_name='Usuario de Acceso'),
        ),
    ]
