# Generated by Django 6.0.2 on 2026-02-13 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Casinos', '0003_alter_casino_creado_en_alter_casino_creado_por_and_more'),
        ('Usuarios', '0003_alter_usuarios_apellido_materno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelevoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría')),
                ('hora_salida_real', models.DateTimeField(help_text='Momento exacto en que el técnico saliente se retira', verbose_name='Hora de Salida')),
                ('estado_entrega', models.CharField(choices=[('limpia', 'Sin Pendientes / Todo Operativo'), ('con_pendientes', 'Con Pendientes Menores'), ('critica', 'Situación Crítica / Urgente')], default='limpia', help_text='Evaluación general de la operación al momento del cambio', max_length=20, verbose_name='Estado de la Sala')),
                ('pendientes_detallados', models.TextField(blank=True, help_text='Lista de máquinas o tareas que quedaron sin concluir', null=True, verbose_name='Pendientes Técnicos')),
                ('novedades_generales', models.TextField(blank=True, help_text='Cualquier comentario relevante sobre el personal o la sala', null=True, verbose_name='Novedades del Turno')),
                ('casino', models.ForeignKey(help_text='Sucursal donde se realiza el cambio de turno', on_delete=django.db.models.deletion.CASCADE, related_name='relevos', to='Casinos.casino', verbose_name='Casino')),
                ('tecnico_entrante', models.ForeignKey(help_text='Usuario que inicia el nuevo turno en la sala', on_delete=django.db.models.deletion.PROTECT, related_name='relevos_recibidos', to='Usuarios.usuarios', verbose_name='Técnico que Recibe')),
                ('tecnico_saliente', models.ForeignKey(help_text='Usuario que finaliza su jornada laboral', on_delete=django.db.models.deletion.PROTECT, related_name='relevos_entregados', to='Usuarios.usuarios', verbose_name='Técnico que Entrega')),
            ],
            options={
                'verbose_name': 'Relevo de Turno',
                'verbose_name_plural': 'Relevos de Turnos',
                'db_table': 'ope_relevo_turnos',
            },
        ),
    ]
