# Generated by Django 6.0.2 on 2026-02-13 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Casinos', '0003_alter_casino_creado_en_alter_casino_creado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaInfraestructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría')),
                ('titulo', models.CharField(help_text='Descripción corta (ej: Apagón zona sur, Gotera fila 5)', max_length=150, verbose_name='Título del Evento')),
                ('categoria', models.CharField(choices=[('electrica', 'Falla Eléctrica / Luz'), ('agua', 'Filtración / Agua / Gotera'), ('clima', 'Climatización / Aire Acondicionado'), ('red_externa', 'Proveedor de Internet / Enlace'), ('obra_civil', 'Estructura / Paredes / Techos'), ('otros', 'Otros Eventos Externos')], help_text='Origen del problema de infraestructura', max_length=30, verbose_name='Categoría del Incidente')),
                ('descripcion', models.TextField(help_text='Relato completo de lo ocurrido y afectaciones visibles', verbose_name='Anotaciones Detalladas')),
                ('severidad', models.CharField(choices=[('baja', 'Baja (Sin afectación)'), ('media', 'Media (Afectación parcial)'), ('alta', 'Alta (Riesgo operativo)'), ('critica', 'Crítica (Cierre de sala/área)')], default='media', help_text='Impacto del evento en la operación de la sala', max_length=20, verbose_name='Nivel de Severidad')),
                ('afecta_operacion', models.BooleanField(default=False, help_text='Marcar si el evento obligó a detener máquinas o servicios', verbose_name='¿Afecta Operación?')),
                ('hora_inicio', models.DateTimeField(help_text='Momento aproximado en que comenzó el incidente', verbose_name='Hora de Inicio')),
                ('hora_fin', models.DateTimeField(blank=True, help_text='Momento en que la situación fue controlada o resuelta', null=True, verbose_name='Hora de Finalización')),
                ('casino', models.ForeignKey(help_text='Sala donde ocurrió el evento de infraestructura', on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_infra', to='Casinos.casino', verbose_name='Casino Afectado')),
            ],
            options={
                'verbose_name': 'Incidencia de Infraestructura',
                'verbose_name_plural': 'Incidencias de Infraestructura',
                'db_table': 'infra_incidencias',
            },
        ),
    ]
