# Generated by Django 6.0.2 on 2026-02-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor monetario de la denominación (ej: 1.00, 0.25)', max_digits=5, unique=True, verbose_name='Valor')),
                ('etiqueta', models.CharField(help_text='Etiqueta para mostrar la denominación (ej: "$1.00", "$0.25 ctv")', max_length=20, verbose_name='Etiqueta')),
            ],
            options={
                'verbose_name': 'Denominación',
                'verbose_name_plural': 'Denominaciones',
                'db_table': 'cat_denominaciones',
            },
        ),
    ]
