# Generated by Django 6.0.2 on 2026-02-13 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Maquinas', '0001_initial'),
        ('Usuarios', '0003_alter_usuarios_apellido_materno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría')),
                ('fecha_mantenimiento', models.DateField(help_text='Día en el que se llevó a cabo la limpieza y revisión programada', verbose_name='Fecha de Ejecución')),
                ('estado_final_maquina', models.CharField(choices=[('operativa', 'Operativa'), ('dañada_operativa', 'Dañada pero Operativa'), ('dañada', 'Dañada'), ('observacion', 'En Observación')], default='operativa', help_text='Estatus en el que queda la máquina tras concluir la rutina', max_length=30, verbose_name='Estado Final')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el estado general (ej: desgaste de piezas, limpieza profunda)', null=True, verbose_name='Observaciones Técnicas')),
                ('maquina', models.ForeignKey(help_text='Selección de la unidad a la que se le realiza la rutina preventiva', on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos_preventivos', to='Maquinas.maquina', verbose_name='Máquina Intervenida')),
                ('tecnico_responsable', models.ForeignKey(help_text='Usuario que realiza físicamente el mantenimiento preventivo', on_delete=django.db.models.deletion.PROTECT, to='Usuarios.usuarios', verbose_name='Técnico Ejecutor')),
            ],
            options={
                'verbose_name': 'Mantenimiento Preventivo',
                'verbose_name_plural': 'Mantenimientos Preventivos',
                'db_table': 'maquina_mantenimientos',
            },
        ),
    ]
