# Generated by Django 6.0.2 on 2026-02-12 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proveedores', '0002_alter_proveedor_casino_alter_proveedor_creado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría')),
                ('nombre_modelo', models.CharField(help_text='Identificador único del modelo de máquina dentro del proveedor', max_length=100, verbose_name='Nombre del Modelo')),
                ('nombre_producto', models.CharField(help_text='Nombre comercial o marca del producto', max_length=100, verbose_name='Nombre del Producto/Marca')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles técnicos adicionales del modelo de máquina', null=True, verbose_name='Descripción Técnica')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_maquinas', to='Proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Modelo de Máquina',
                'verbose_name_plural': 'Modelos de Máquinas',
                'db_table': 'maquina_modelos',
                'unique_together': {('proveedor', 'nombre_modelo')},
            },
        ),
    ]
