# Generated by Django 6.0.2 on 2026-02-13 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Casinos', '0003_alter_casino_creado_en_alter_casino_creado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría')),
                ('nombre', models.CharField(help_text='Nombre de la herramienta o consumible (ej: Cautín, Tornillos M3)', max_length=150, verbose_name='Nombre del Artículo')),
                ('tipo', models.CharField(choices=[('herramienta', 'Herramienta'), ('consumible', 'Consumible')], default='consumible', help_text='Categorización para separar herramientas de consumibles', max_length=20, verbose_name='Tipo de Artículo')),
                ('cantidad', models.PositiveIntegerField(default=0, help_text='Existencia física actual en la sala', verbose_name='Cantidad')),
                ('casino', models.ForeignKey(help_text='Sala a la que pertenece este artículo', on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='Casinos.casino', verbose_name='Casino')),
            ],
            options={
                'verbose_name': 'Artículo de Inventario',
                'verbose_name_plural': 'Artículos de Inventario',
                'db_table': 'alm_inventario_sala',
            },
        ),
    ]
