# Generated by Django 6.0.2 on 2026-02-13 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Maquinas', '0001_initial'),
        ('Usuarios', '0003_alter_usuarios_apellido_materno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría')),
                ('folio', models.CharField(editable=False, help_text='Identificador único del ticket (generado automáticamente)', max_length=20, unique=True)),
                ('categoria', models.CharField(choices=[('hardware', 'Hardware'), ('perifericos', 'Periféricos'), ('software', 'Software'), ('red', 'Red / Comunicación'), ('otros', 'Otros')], help_text='Categoría del problema reportado', max_length=30)),
                ('subcategoria', models.CharField(help_text='Subcategoría o detalle específico del problema', max_length=50)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica'), ('emergencia', 'Emergencia'), ('sin_prioridad', 'Sin Prioridad')], default='media', max_length=20)),
                ('descripcion_problema', models.TextField(help_text='Descripción detallada del problema reportado')),
                ('estado_ciclo', models.CharField(choices=[('abierto', 'Abierto'), ('proceso', 'En Proceso'), ('espera', 'En Espera'), ('cerrado', 'Cerrado'), ('reabierto', 'Reabierto')], default='abierto', max_length=20)),
                ('notas_seguimiento', models.TextField(blank=True, help_text='Notas adicionales para el seguimiento del ticket', null=True)),
                ('explicacion_cierre', models.TextField(blank=True, help_text='Explicación o motivo del cierre del ticket', null=True)),
                ('contador_reaperturas', models.PositiveIntegerField(default=0, help_text='Número de veces que el ticket ha sido reabierto')),
                ('maquina', models.ForeignKey(help_text='Máquina relacionada con el problema reportado', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Maquinas.maquina')),
                ('reportante', models.ForeignKey(help_text='Usuario que reporta el problema', on_delete=django.db.models.deletion.PROTECT, related_name='tickets_reportados', to='Usuarios.usuarios')),
                ('tecnico_asignado', models.ForeignKey(blank=True, help_text='Técnico asignado al ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='Usuarios.usuarios')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
                'ordering': ['-creado_en'],
            },
        ),
    ]
