# Generated by Django 6.0.2 on 2026-02-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subcategoria',
            field=models.CharField(blank=True, help_text='Subcategoría o detalle específico del problema', max_length=50, null=True),
        ),
    ]
