# Generated by Django 6.0.2 on 2026-02-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0002_alter_ticket_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estado_maquina_reportado',
            field=models.CharField(blank=True, choices=[('OPERATIVA', 'Operativa y Sin Fallas'), ('DAÑADA_OPERATIVA', 'Dañada pero Operativa (Con Fallas)'), ('DAÑADA', 'Dañada y No Operativa (No Funciona)'), ('MANTENIMIENTO', 'En Mantenimiento o Reparación'), ('OBSERVACION', 'En Observación o Pruebas de Funcionamiento'), ('PRUEBAS', 'Realizando Pruebas de Funcionamiento (No Disponible)')], help_text='Estado al que se actualizó la máquina al reportar el ticket', max_length=30, null=True),
        ),
    ]
