# Generated by Django 6.0.2 on 2026-02-12 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Casinos', '0003_alter_casino_creado_en_alter_casino_creado_por_and_more'),
        ('Denominaciones', '0001_initial'),
        ('ModelosMaquinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría')),
                ('uid_sala', models.CharField(help_text='Identificador único dentro de la sala del casino (ej. A01, B12)', max_length=20)),
                ('numero_serie', models.CharField(help_text='Número de serie único de la máquina', max_length=100, unique=True)),
                ('ip_maquina', models.GenericIPAddressField(help_text='Dirección IP asignada a la máquina (opcional, pero debe ser única si se proporciona)')),
                ('juego', models.CharField(help_text='Nombre del juego o título que ofrece la máquina o MULTIJUEGO', max_length=150)),
                ('ubicacion_piso', models.CharField(help_text='Piso o área del casino donde se encuentra la máquina (ej. Piso 1, VIP)', max_length=50)),
                ('ubicacion_sala', models.CharField(help_text='Sala o sección específica dentro del piso del casino', max_length=100)),
                ('coordenada_x', models.PositiveIntegerField(default=0, help_text='Coordenada X en la cuadrícula del piso del casino (entero positivo)')),
                ('coordenada_y', models.PositiveIntegerField(default=0, help_text='Coordenada Y en la cuadrícula del piso del casino (entero positivo)')),
                ('estado_actual', models.CharField(choices=[('OPERATIVA', 'Operativa y Sin Fallas'), ('DAÑADA_OPERATIVA', 'Dañada pero Operativa (Con Fallas)'), ('DAÑADA', 'Dañada y No Operativa (No Funciona)'), ('MANTENIMIENTO', 'En Mantenimiento o Reparación'), ('OBSERVACION', 'En Observación o Pruebas de Funcionamiento'), ('PRUEBAS', 'Realizando Pruebas de Funcionamiento (No Disponible)')], default='OPERATIVA', help_text='Estado técnico actual de la máquina', max_length=30)),
                ('contador_fallas', models.PositiveIntegerField(default=0, help_text='Contador de fallas encontradas en la máquina')),
                ('ultimo_mantenimiento', models.DateField(blank=True, help_text='Fecha del último mantenimiento realizado a la máquina', null=True)),
                ('fecha_vencimiento_licencia', models.DateField(blank=True, help_text='Fecha de vencimiento de la licencia de uso de la máquina', null=True)),
                ('casino', models.ForeignKey(help_text='Casino al que pertenece esta máquina', on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='Casinos.casino')),
                ('denominaciones', models.ManyToManyField(help_text='Denominaciones aceptadas por la máquina (puede ser múltiple)', related_name='maquinas', to='Denominaciones.denominacion')),
                ('modelo', models.ForeignKey(help_text='Modelo específico de la máquina, con detalles técnicos y características', on_delete=django.db.models.deletion.PROTECT, related_name='maquinas', to='ModelosMaquinas.modelomaquina')),
            ],
            options={
                'db_table': 'maquinas',
                'unique_together': {('casino', 'uid_sala')},
            },
        ),
    ]
