# Generated by Django 6.0.2 on 2026-02-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maquinas', '0002_alter_maquina_ubicacion_piso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='numero_serie',
            field=models.CharField(help_text='Número de serie único de la máquina', max_length=100),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='ubicacion_piso',
            field=models.CharField(choices=[('PISO_1', 'Piso 1'), ('PISO_2', 'Piso 2'), ('PISO_3', 'Piso 3'), ('PISO_4', 'Piso 4'), ('PLANTA_BAJA', 'Planta Baja'), ('VIP', 'Área VIP'), ('TERRAZA', 'Terraza'), ('SOTANO', 'Sótano'), ('OTRO', 'Otro')], default='PISO_1', help_text='Piso donde se encuentra la máquina (selección predefinida)', max_length=50),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='ubicacion_sala',
            field=models.CharField(choices=[('SALA_A', 'Sala A'), ('SALA_B', 'Sala B'), ('SALA_C', 'Sala C'), ('SALA_D', 'Sala D'), ('SALA_PRINCIPAL', 'Sala Principal'), ('ZONA_FUMADORES', 'Zona Fumadores'), ('ZONA_NO_FUMADORES', 'Zona No Fumadores'), ('ZONA_ALTA_DENOMINACION', 'Zona Alta Denominación'), ('BAR', 'Bar / Restaurante'), ('ENTRADA', 'Entrada / Lobby'), ('OTRO', 'Otro')], default='SALA_PRINCIPAL', help_text='Sala o sección específica dentro del piso del casino (selección predefinida)', max_length=100),
        ),
    ]
