# Generated by Django 6.0.2 on 2026-02-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuracion', models.JSONField(default=list)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Menú',
                'verbose_name_plural': 'Configuraciones de Menú',
                'db_table': 'menu_config',
            },
        ),
    ]
