# Generated by Django 6.0.2 on 2026-02-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, null=True, verbose_name='Notas de Auditoría')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Casino')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Casino',
                'verbose_name_plural': 'Casinos',
                'db_table': 'casinos',
                'ordering': ['nombre'],
            },
        ),
    ]
