# Generated by Django 6.0.2 on 2026-02-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='encargado',
            field=models.CharField(blank=True, help_text='Nombre del encargado del casino (opcional)', max_length=100, null=True, verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='ciudad',
            field=models.CharField(help_text='Ciudad donde se encuentra el casino', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='direccion',
            field=models.CharField(help_text='Dirección completa del casino', max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='nombre',
            field=models.CharField(help_text='Nombre oficial del casino', max_length=100, unique=True, verbose_name='Nombre del Casino'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono del casino (opcional)', max_length=20, null=True, verbose_name='Teléfono de Contacto'),
        ),
    ]
