# Generated by Django 6.0.2 on 2026-02-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casinos', '0002_casino_encargado_alter_casino_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='creado_por',
            field=models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='encargado',
            field=models.CharField(blank=True, help_text='Nombre del responsable operativo del casino', max_length=100, null=True, verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='esta_activo',
            field=models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='modificado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='modificado_por',
            field=models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='notas_internas',
            field=models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría'),
        ),
    ]
