# Generated by Django 6.0.2 on 2026-02-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casinos', '0003_alter_casino_creado_en_alter_casino_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='horario_apertura',
            field=models.TimeField(blank=True, help_text='Hora de apertura del casino', null=True, verbose_name='Horario de Apertura'),
        ),
        migrations.AddField(
            model_name='casino',
            name='horario_cierre',
            field=models.TimeField(blank=True, help_text='Hora de cierre del casino', null=True, verbose_name='Horario de Cierre'),
        ),
        migrations.AddField(
            model_name='casino',
            name='identificador',
            field=models.CharField(blank=True, help_text='Código único para identificar el casino (ej. código interno o número de licencia)', max_length=50, null=True, unique=True, verbose_name='Identificador'),
        ),
    ]
