# Generated by Django 6.0.2 on 2026-02-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casinos', '0004_casino_horario_apertura_casino_horario_cierre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='grid_height',
            field=models.PositiveIntegerField(default=50, help_text='Número de filas del mapa de sala (alto de la cuadrícula). Default: 50', verbose_name='Alto de Cuadrícula'),
        ),
        migrations.AddField(
            model_name='casino',
            name='grid_width',
            field=models.PositiveIntegerField(default=50, help_text='Número de columnas del mapa de sala (ancho de la cuadrícula). Default: 50', verbose_name='Ancho de Cuadrícula'),
        ),
    ]
