# Generated by Django 6.0.2 on 2026-02-21 22:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Casinos', '0005_casino_grid_height_casino_grid_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=100, verbose_name='Tabla Afectada')),
                ('registro_id', models.CharField(max_length=50, verbose_name='ID de Registro')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar')], max_length=20, verbose_name='Acción Realizada')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos Nuevos')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Evento')),
                ('casino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Casinos.casino', verbose_name='Casino Relacionado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'auditoria_global',
                'ordering': ['-fecha'],
            },
        ),
    ]
