# Generated by Django 6.0.2 on 2026-02-13 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Casinos', '0003_alter_casino_creado_en_alter_casino_creado_por_and_more'),
        ('Proveedores', '0002_alter_proveedor_casino_alter_proveedor_creado_en_and_more'),
        ('Usuarios', '0003_alter_usuarios_apellido_materno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaServicioExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría')),
                ('nombre_tecnico_externo', models.CharField(help_text='Nombre completo de la persona enviada por el proveedor', max_length=150, verbose_name='Nombre del Técnico Externo')),
                ('area_acceso', models.CharField(choices=[('site_servidores', 'Site de Servidores'), ('racks_sala', 'Racks de Sala'), ('area_maquinas', 'Área de Máquinas (Piso)'), ('oficinas_tecnicas', 'Oficinas Técnicas'), ('boveda_conteo', 'Bóveda / Área de Conteo')], help_text='Zona crítica donde el externo realizó sus labores', max_length=50, verbose_name='Área de Acceso')),
                ('tipo_servicio', models.CharField(choices=[('internet_enlaces', 'Internet y Enlaces'), ('climatizacion', 'Aire Acondicionado / Clima'), ('energia_ups', 'Energía / UPS / Plantas'), ('seguridad_cctv', 'Seguridad / CCTV'), ('limpieza_profunda', 'Limpieza Especializada')], help_text='Motivo técnico de la visita externa', max_length=50, verbose_name='Tipo de Servicio')),
                ('descripcion_actividad', models.TextField(help_text='Detalle de los cambios o revisiones efectuadas por el externo', verbose_name='Actividades Realizadas')),
                ('hora_entrada', models.DateTimeField(help_text='Momento en que el externo ingresó al área técnica', verbose_name='Hora de Entrada')),
                ('hora_salida', models.DateTimeField(blank=True, help_text='Momento en que el externo se retiró del área', null=True, verbose_name='Hora de Salida')),
                ('casino', models.ForeignKey(help_text='Sucursal donde se realiza el servicio externo', on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_externas', to='Casinos.casino', verbose_name='Casino')),
                ('empresa_proveedora', models.ForeignKey(help_text='Compañía externa que brinda el servicio técnico', on_delete=django.db.models.deletion.PROTECT, related_name='servicios_realizados', to='Proveedores.proveedor', verbose_name='Empresa Proveedora')),
                ('supervisor_interno', models.ForeignKey(help_text='Personal interno que vigila y autoriza el acceso', on_delete=django.db.models.deletion.PROTECT, related_name='supervisiones_externas', to='Usuarios.usuarios', verbose_name='Supervisor de Sistemas')),
            ],
            options={
                'verbose_name': 'Auditoría de Servicio Externo',
                'verbose_name_plural': 'Auditorías de Servicios Externos',
                'db_table': 'aud_servicios_externos',
            },
        ),
    ]
