# Generated by Django 6.0.2 on 2026-02-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditoriasExternas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaservicioexterno',
            name='area_acceso',
            field=models.CharField(choices=[('site_servidores', 'Site de Servidores'), ('racks_sala', 'Racks de Sala'), ('area_maquinas', 'Área de Máquinas (Piso)'), ('oficinas_tecnicas', 'Oficinas Técnicas'), ('boveda_conteo', 'Bóveda / Área de Conteo'), ('sala', 'Sala de Juegos'), ('cocina', 'Cocina'), ('comedor', 'Comedor'), ('cajas', 'Cajas'), ('jv', 'JV / Monitoreo')], help_text='Zona crítica donde el externo realizó sus labores', max_length=50, verbose_name='Área de Acceso'),
        ),
        migrations.AlterField(
            model_name='auditoriaservicioexterno',
            name='tipo_servicio',
            field=models.CharField(choices=[('internet_enlaces', 'Internet y Enlaces'), ('climatizacion', 'Aire Acondicionado / Clima'), ('energia_ups', 'Energía / UPS / Plantas'), ('seguridad_cctv', 'Seguridad / CCTV'), ('limpieza_profunda', 'Limpieza Especializada'), ('mantenimiento_equipo', 'Mantenimiento de Equipo Técnico'), ('fumigacion', 'Fumigación / Sanitización'), ('obra_civil', 'Reparaciones Locales')], help_text='Motivo técnico de la visita externa', max_length=50, verbose_name='Tipo de Servicio'),
        ),
    ]
