# Generated by Django 6.0.2 on 2026-02-13 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Casinos', '0003_alter_casino_creado_en_alter_casino_creado_por_and_more'),
        ('ModelosMaquinas', '0001_initial'),
        ('Usuarios', '0003_alter_usuarios_apellido_materno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría')),
                ('titulo_guia', models.CharField(help_text='Nombre claro del problema o procedimiento (ej: Error de RAM en EGT)', max_length=200, verbose_name='Título de la Guía')),
                ('categoria', models.CharField(choices=[('reparacion', 'Guía de Reparación'), ('configuracion', 'Manual de Configuración'), ('limpieza', 'Procedimiento de Limpieza'), ('error_code', 'Diccionario de Códigos de Error')], default='reparacion', help_text='Tipo de documento para facilitar la búsqueda', max_length=50, verbose_name='Categoría')),
                ('archivo_pdf', models.FileField(help_text='Documento oficial con la resolución o manual técnico', upload_to='wiki_tecnica/pdfs/', verbose_name='Archivo PDF')),
                ('puntos_reconocimiento', models.PositiveIntegerField(default=0, help_text='Puntos acumulados por la utilidad de esta guía para el equipo', verbose_name='Puntos de Medalla')),
                ('autor', models.ForeignKey(help_text='Técnico que redactó y subió el material (Para reconocimiento público)', on_delete=django.db.models.deletion.PROTECT, related_name='guias_creadas', to='Usuarios.usuarios', verbose_name='Autor de la Guía')),
                ('casino_origen', models.ForeignKey(blank=True, help_text='Sucursal donde se originó la solución o el caso de estudio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_locales', to='Casinos.casino', verbose_name='Casino de Origen')),
                ('modelo_relacionado', models.ForeignKey(help_text='Modelo específico al que aplica esta documentación', on_delete=django.db.models.deletion.CASCADE, related_name='manuales', to='ModelosMaquinas.modelomaquina', verbose_name='Modelo de Máquina')),
            ],
            options={
                'verbose_name': 'Guía Técnica',
                'verbose_name_plural': 'Wiki de Conocimiento',
                'db_table': 'wiki_tecnica',
            },
        ),
    ]
