# Generated by Django 6.0.2 on 2026-02-22 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wiki', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wikitecnica',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Guía Técnica', 'verbose_name_plural': 'Wiki de Conocimiento'},
        ),
        migrations.AddField(
            model_name='wikitecnica',
            name='estado',
            field=models.CharField(choices=[('pendiente_revision', 'Pendiente de Revisión'), ('aprobada', 'Aprobada'), ('publicada', 'Publicada'), ('rechazada', 'Rechazada')], db_index=True, default='pendiente_revision', help_text='Ciclo de vida: pendiente_revision → aprobada → publicada (o rechazada)', max_length=30, verbose_name='Estado de la Guía'),
        ),
        migrations.AddField(
            model_name='wikitecnica',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que el administrador tomó acción sobre la guía', null=True, verbose_name='Fecha de Revisión'),
        ),
        migrations.AddField(
            model_name='wikitecnica',
            name='nota_revision',
            field=models.TextField(blank=True, help_text='Comentario del administrador al aprobar, rechazar o publicar la guía', null=True, verbose_name='Nota del Revisor'),
        ),
        migrations.AddField(
            model_name='wikitecnica',
            name='revisada_por',
            field=models.ForeignKey(blank=True, help_text='Administrador que aprobó, rechazó o publicó la guía', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisada por'),
        ),
        migrations.AlterField(
            model_name='wikitecnica',
            name='puntos_reconocimiento',
            field=models.PositiveIntegerField(default=0, help_text='Puntos que el administrador asigna al técnico autor al publicar la guía. Se suman automáticamente a puntos_gamificacion del usuario.', verbose_name='Puntos de Reconocimiento'),
        ),
    ]
