# Generated by Django 6.0.2 on 2026-02-22 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Casinos', '0005_casino_grid_height_casino_grid_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecompensaGamificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría')),
                ('titulo', models.CharField(help_text='Nombre de la recompensa (ej: Día libre adicional, Bono de alimentación)', max_length=150, verbose_name='Título de la Recompensa')),
                ('descripcion', models.TextField(help_text='Detalle completo de la recompensa: qué incluye, cómo se reclama, vigencia, etc.', verbose_name='Descripción')),
                ('costo_puntos', models.PositiveIntegerField(help_text='Cantidad de puntos de gamificación necesarios para canjear esta recompensa', verbose_name='Costo en Puntos')),
                ('activo', models.BooleanField(default=True, help_text='Controla la visibilidad de la recompensa. Desactívala para retirarla sin eliminarla.', verbose_name='Activo')),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Cantidad máxima de canjes permitidos. Deja vacío para stock ilimitado.', null=True, verbose_name='Stock Disponible')),
                ('casino', models.ForeignKey(help_text='Sucursal que ofrece esta recompensa. Solo los técnicos de este casino pueden verla.', on_delete=django.db.models.deletion.CASCADE, related_name='recompensas_gamificacion', to='Casinos.casino', verbose_name='Casino')),
            ],
            options={
                'verbose_name': 'Recompensa de Gamificación',
                'verbose_name_plural': 'Tienda de Recompensas',
                'db_table': 'recompensa_gamificacion',
                'ordering': ['costo_puntos'],
            },
        ),
        migrations.CreateModel(
            name='CanjeRecompensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría')),
                ('puntos_descontados', models.PositiveIntegerField(help_text='Puntos deducidos al momento del canje (snapshot del costo en ese instante)', verbose_name='Puntos Descontados')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Entrega'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', help_text='El personal de gerencia actualiza este estado al entregar la recompensa', max_length=20, verbose_name='Estado del Canje')),
                ('nota_gerencia', models.TextField(blank=True, help_text='Observaciones de gerencia al procesar el canje', null=True, verbose_name='Nota de Gerencia')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó el canje', on_delete=django.db.models.deletion.PROTECT, related_name='canjes_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
                ('recompensa', models.ForeignKey(help_text='Recompensa seleccionada por el técnico', on_delete=django.db.models.deletion.PROTECT, related_name='canjes', to='Gamificacion.recompensagamificacion', verbose_name='Recompensa Canjeada')),
            ],
            options={
                'verbose_name': 'Canje de Recompensa',
                'verbose_name_plural': 'Historial de Canjes',
                'db_table': 'canje_recompensa',
                'ordering': ['-creado_en'],
            },
        ),
    ]
