# Generated by Django 6.0.2 on 2026-02-13 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tickets', '0001_initial'),
        ('Usuarios', '0003_alter_usuarios_apellido_materno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría')),
                ('tipo_intervencion', models.CharField(choices=[('correctiva', 'Correctiva (Reparación)'), ('ajuste', 'Ajuste / Calibración'), ('instalacion', 'Instalación / Movimiento'), ('actualización', 'Actualización de Software'), ('diagnostico', 'Solo Diagnóstico')], help_text='Categoría del trabajo realizado en la máquina', max_length=30, verbose_name='Tipo de Intervención')),
                ('descripcion_trabajo', models.TextField(help_text='Detalle técnico de las pruebas y acciones ejecutadas', verbose_name='Descripción del Trabajo')),
                ('resultado_intervencion', models.CharField(choices=[('exitosa', 'Reparación Exitosa'), ('parcial', 'Reparación Parcial'), ('fallida', 'Prueba Fallida'), ('espera_refaccion', 'En espera de Refacción')], help_text='Estatus final de la reparación tras las pruebas', max_length=30, verbose_name='Resultado de la Intervención')),
                ('estado_maquina_resultante', models.CharField(choices=[('operativa', 'Operativa'), ('dañada_operativa', 'Dañada pero Operativa'), ('dañada', 'Dañada'), ('mantenimiento', 'En Mantenimiento')], help_text='Estatus en el que se deja la unidad físicamente en sala', max_length=30, verbose_name='Estado de Máquina Resultante')),
                ('finaliza_ticket', models.BooleanField(default=False, help_text='Marcar únicamente si esta acción resuelve el folio por completo', verbose_name='Cierra Ticket')),
                ('ticket', models.ForeignKey(help_text='Vínculo obligatorio al folio del ticket en cuestión', on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='Tickets.ticket', verbose_name='Ticket Relacionado')),
                ('usuario_tecnico', models.ForeignKey(help_text='Usuario técnico que realiza la anotación en bitácora', on_delete=django.db.models.deletion.PROTECT, to='Usuarios.usuarios', verbose_name='Técnico Responsable')),
            ],
            options={
                'verbose_name': 'Entrada de Bitácora',
                'verbose_name_plural': 'Bitácoras Técnicas',
                'db_table': 'tickets_bitacora',
            },
        ),
    ]
