# Generated by Django 6.0.2 on 2026-02-06 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, null=True, verbose_name='Notas de Auditoría')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de Funciones')),
                ('nivel', models.PositiveSmallIntegerField(help_text='Escala de 0 a 200 para determinar prioridad de permisos.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='Nivel de Jerarquía')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['-nivel'],
            },
        ),
    ]
