# Generated by Django 6.0.2 on 2026-02-12 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='creado_por',
            field=models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Detalle de las responsabilidades y alcance del rol', null=True, verbose_name='Descripción de Funciones'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='esta_activo',
            field=models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='modificado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='modificado_por',
            field=models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nivel',
            field=models.PositiveSmallIntegerField(help_text='Escala jerárquica de 0 a 200, mayor nivel = mayores privilegios', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='Nivel de Jerarquía'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(help_text='Identificador único del rol (ej: Administrador, Operador)', max_length=50, unique=True, verbose_name='Nombre del Rol'),
        ),
        migrations.AlterField(
            model_name='rol',
            name='notas_internas',
            field=models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría'),
        ),
    ]
