# Generated by Django 6.0.2 on 2026-02-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0002_alter_rol_creado_en_alter_rol_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['nombre'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.RemoveField(
            model_name='rol',
            name='nivel',
        ),
    ]
