# Generated by Django 6.0.2 on 2026-03-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Roles', '0003_alter_rol_options_remove_rol_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='nivel_jerarquia',
            field=models.IntegerField(default=1, help_text='Nivel de acceso del rol (ej: Administrador=10, Operador=1)', verbose_name='Nivel de Jerarquía'),
        ),
    ]
