# Generated by Django 6.0.2 on 2026-02-13 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Casinos', '0003_alter_casino_creado_en_alter_casino_creado_por_and_more'),
        ('Usuarios', '0003_alter_usuarios_apellido_materno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría')),
                ('titulo', models.CharField(help_text='Encabezado de la alerta', max_length=150, verbose_name='Título')),
                ('contenido', models.TextField(help_text='Detalle completo del mensaje', verbose_name='Contenido')),
                ('nivel', models.CharField(choices=[('urgente', 'Urgente (Acción Inmediata)'), ('alerta', 'Alerta (Atención Requerida)'), ('informativa', 'Informativa (Solo lectura)')], default='informativa', max_length=20, verbose_name='Nivel de Prioridad')),
                ('tipo', models.CharField(choices=[('ticket', 'Gestión de Tickets'), ('infraestructura', 'Incidencia de Infraestructura'), ('wiki', 'Nueva Guía en Wiki'), ('sistema', 'Aviso del Sistema')], max_length=20, verbose_name='Tipo de Notificación')),
                ('es_global', models.BooleanField(default=False, help_text='Marcar para que todos los usuarios de Sakai la vean', verbose_name='¿Es Global?')),
                ('es_del_director', models.BooleanField(default=False, help_text='Si es True, la notificación durará 7 días en el sistema', verbose_name='Aviso de Dirección')),
                ('leido', models.BooleanField(default=False, help_text='Indica si el usuario ya visualizó el mensaje', verbose_name='Estatus de Lectura')),
                ('casino_destino', models.ForeignKey(blank=True, help_text='Si se define, la verán los técnicos de esta sala', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_sala', to='Casinos.casino', verbose_name='Casino Destino')),
                ('usuario_destino', models.ForeignKey(blank=True, help_text='Si se define, solo este usuario recibirá la alerta', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_personales', to='Usuarios.usuarios', verbose_name='Usuario Destino')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'sys_notificaciones',
                'indexes': [models.Index(fields=['creado_en', 'leido', 'es_del_director'], name='sys_notific_creado__f3340d_idx')],
            },
        ),
    ]
