# Generated by Django 6.0.2 on 2026-02-17 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notificaciones', '0001_initial'),
        ('Roles', '0003_alter_rol_options_remove_rol_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='rol_destino',
            field=models.ForeignKey(blank=True, help_text='Si se define junto con casino, solo usuarios de ese rol en ese casino verán la notificación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_rol', to='Roles.rol', verbose_name='Rol Destino'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('ticket', 'Gestión de Tickets'), ('infraestructura', 'Incidencia de Infraestructura'), ('wiki', 'Nueva Guía en Wiki'), ('sistema', 'Aviso del Sistema'), ('DIRECTOR', 'Mensaje de Dirección')], max_length=20, verbose_name='Tipo de Notificación'),
        ),
    ]
