# Generated by Django 6.0.2 on 2026-02-17 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casinos', '0004_casino_horario_apertura_casino_horario_cierre_and_more'),
        ('Notificaciones', '0002_notificacion_rol_destino_alter_notificacion_tipo'),
        ('Roles', '0003_alter_rol_options_remove_rol_nivel'),
        ('Usuarios', '0004_usuarios_eulaaceptada'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría')),
                ('fecha_visto', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que el usuario marcó la notificación como vista', verbose_name='Fecha de Lectura')),
            ],
            options={
                'verbose_name': 'Lectura de Notificación',
                'verbose_name_plural': 'Lecturas de Notificaciones',
                'db_table': 'sys_notificaciones_usuarios',
            },
        ),
        migrations.RemoveIndex(
            model_name='notificacion',
            name='sys_notific_creado__f3340d_idx',
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['creado_en', 'es_del_director'], name='sys_notific_creado__134ee0_idx'),
        ),
        migrations.AddField(
            model_name='notificacionusuario',
            name='notificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='Notificaciones.notificacion', verbose_name='Notificación'),
        ),
        migrations.AddField(
            model_name='notificacionusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_vistas', to='Usuarios.usuarios', verbose_name='Usuario'),
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='leido',
        ),
        migrations.AddIndex(
            model_name='notificacionusuario',
            index=models.Index(fields=['usuario', 'fecha_visto'], name='sys_notific_usuario_eede52_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionusuario',
            index=models.Index(fields=['notificacion', 'usuario'], name='sys_notific_notific_efd928_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificacionusuario',
            unique_together={('notificacion', 'usuario')},
        ),
    ]
