# Generated by Django 6.0.2 on 2026-02-19 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolucionNexus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('ERROR', 'Error (Bug)'), ('VISUAL', 'Visual (Estilo)'), ('COMPORTAMIENTO', 'Comportamiento (Lógica)'), ('FUNCIONALIDAD', 'Funcionalidad (Nuevo Módulo)'), ('REPORTE', 'Reporte (Gráfica/Página)')], default='ERROR', max_length=20)),
                ('estado', models.CharField(choices=[('NO_REVISADO', 'No Revisado'), ('POR_REVISAR', 'Abierto por Revisar'), ('ANALIZANDO', 'Analizando Requerimientos'), ('ADQUISICION', 'Estudio de Mercado / Adquisición de Info'), ('MAQUETACION', 'Iniciando Maquetación'), ('DESARROLLO', 'En Desarrollo'), ('PRUEBAS', 'Pruebas / QA'), ('COMPLETADO', 'Completado')], default='NO_REVISADO', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_evolucion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evolución NEXUS',
                'verbose_name_plural': 'Evoluciones NEXUS',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
