# Generated by Django 6.0.2 on 2026-02-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvolucionNexus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucionnexus',
            name='categoria',
            field=models.CharField(choices=[('ERROR', 'Error (Bug)'), ('VISUAL', 'Visual (Estilo)'), ('COMPORTAMIENTO', 'Comportamiento (Lógica)'), ('FUNCIONALIDAD', 'Funcionalidad (Nuevo Módulo)'), ('CREAR', 'Crear Nuevo ...')], default='ERROR', max_length=20),
        ),
    ]
