# Generated by Django 6.0.2 on 2026-02-12 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Casinos', '0002_casino_encargado_alter_casino_ciudad_and_more'),
        ('Roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, null=True, verbose_name='Notas de Auditoría')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('session_token', models.CharField(blank=True, max_length=255, null=True)),
                ('ultima_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0)),
                ('requiere_cambio_password', models.BooleanField(default=False)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Casinos.casino')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Roles.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
    ]
