# Generated by Django 6.0.2 on 2026-02-12 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casinos', '0003_alter_casino_creado_en_alter_casino_creado_por_and_more'),
        ('Roles', '0002_alter_rol_creado_en_alter_rol_creado_por_and_more'),
        ('Usuarios', '0002_usuarios_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='apellido_materno',
            field=models.CharField(blank=True, help_text='Segundo apellido del usuario', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='apellido_paterno',
            field=models.CharField(help_text='Primer apellido del usuario', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='casino',
            field=models.ForeignKey(help_text='Casino al que pertenece el usuario', on_delete=django.db.models.deletion.PROTECT, to='Casinos.casino'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='creado_por',
            field=models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(help_text='Correo electrónico institucional del usuario', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='esta_activo',
            field=models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='intentos_fallidos',
            field=models.PositiveSmallIntegerField(default=0, help_text='Contador de intentos de acceso fallidos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='modificado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='modificado_por',
            field=models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombres',
            field=models.CharField(help_text='Nombre(s) del usuario', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='notas_internas',
            field=models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='refresh_token',
            field=models.CharField(blank=True, help_text='Token para renovar sesión (generado automáticamente)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='requiere_cambio_password',
            field=models.BooleanField(default=False, help_text='Indica si el usuario debe cambiar su contraseña en el próximo acceso'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(help_text='Rol que determina los permisos del usuario', on_delete=django.db.models.deletion.PROTECT, to='Roles.rol'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='session_token',
            field=models.CharField(blank=True, help_text='Token de sesión activa (generado automáticamente)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='ultima_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Última dirección IP desde donde se conectó', null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Información del navegador/dispositivo utilizado', null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(help_text='Nombre de usuario único para acceso al sistema', max_length=50, unique=True),
        ),
    ]
