# Generated by Django 6.0.2 on 2026-02-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_usuarios_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='EULAAceptada',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha aceptado el acuerdo de licencia de uso de software (EULA)'),
        ),
    ]
