# Generated by Django 6.0.2 on 2026-02-19 17:19

import Usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_usuarios_eulaaceptada'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='avatar',
            field=models.FileField(blank=True, help_text='Imagen de perfil del usuario', null=True, upload_to=Usuarios.models.custom_upload_to),
        ),
    ]
