# Generated by Django 6.0.2 on 2026-02-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_usuarios_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='puntos_gamificacion',
            field=models.PositiveIntegerField(default=0, help_text='Puntos de reconocimiento acumulados por contribuciones a la Wiki Técnica. Se otorgan cuando el administrador aprueba y publica una guía enviada por el técnico.'),
        ),
    ]
