# Generated by Django 6.0.2 on 2026-02-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_gamificacion_wiki_flujo_aprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='puntos_gamificacion_historico',
            field=models.PositiveIntegerField(default=0, help_text='Total acumulado de puntos ganados en toda la trayectoria del técnico. Solo se incrementa, nunca disminuye. Refleja el esfuerzo real independientemente de canjes realizados. Se usa para calcular el rango.'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='puntos_gamificacion',
            field=models.PositiveIntegerField(default=0, help_text='Puntos disponibles actualmente. Se suman al ganar reconocimientos y se descuentan al canjear recompensas en la tienda.'),
        ),
    ]
