# Generated by Django 6.0.2 on 2026-03-02 22:36

import VaciosTickets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Casinos', '0005_casino_grid_height_casino_grid_width'),
        ('Maquinas', '0003_alter_maquina_numero_serie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCasino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría')),
                ('umbral_autorizacion', models.DecimalField(decimal_places=2, default=1000, help_text='Monto a partir del cual el ticket requiere aprobación gerencial', max_digits=10, verbose_name='Umbral de Autorización ($)')),
                ('siempre_requiere_autorizacion', models.BooleanField(default=False, help_text='Si está activado, todo ticket de este casino pasa a estado pendiente sin importar el monto', verbose_name='Siempre Requiere Autorización')),
                ('casino', models.OneToOneField(help_text='Casino al que pertenece esta configuración', on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_vacios', to='Casinos.casino', verbose_name='Casino')),
            ],
            options={
                'verbose_name': 'Configuración de Casino (Vacíos)',
                'verbose_name_plural': 'Configuraciones de Casino (Vacíos)',
            },
        ),
        migrations.CreateModel(
            name='TicketVacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True, help_text='Indica si el registro está activo o fue eliminado lógicamente', verbose_name='Estado Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización', verbose_name='Última Modificación')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó el registro', max_length=100, null=True, verbose_name='Creado por')),
                ('modificado_por', models.CharField(blank=True, help_text='Usuario que realizó la última modificación', max_length=100, null=True, verbose_name='Modificado por')),
                ('notas_internas', models.TextField(blank=True, help_text='Observaciones internas para seguimiento y auditoría', null=True, verbose_name='Notas de Auditoría')),
                ('cliente_nombre', models.CharField(help_text='Nombre completo del cliente que reporta el vacío', max_length=200, verbose_name='Nombre del Cliente')),
                ('monto_extraviado', models.DecimalField(decimal_places=2, help_text='Cantidad de dinero que el cliente cargó y no fue acreditada', max_digits=10, verbose_name='Monto Extraviado ($)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_auditoria', models.DateTimeField(blank=True, help_text='Timestamp en que el gerente emitió su veredicto', null=True, verbose_name='Fecha de Auditoría')),
                ('foto_ultimas_operaciones', models.ImageField(help_text='Captura de las últimas transacciones registradas en la máquina', upload_to=VaciosTickets.models.vacio_foto_upload, verbose_name='Foto: Últimas Operaciones')),
                ('foto_carga_sistema', models.ImageField(help_text='Captura de la pantalla del sistema en el momento de la carga', upload_to=VaciosTickets.models.vacio_foto_upload, verbose_name='Foto: Carga en Sistema')),
                ('foto_seguimiento_slot', models.ImageField(help_text='Captura del seguimiento de slot / historial de la máquina', upload_to=VaciosTickets.models.vacio_foto_upload, verbose_name='Foto: Seguimiento Slot')),
                ('foto_recarga_error', models.ImageField(help_text='Captura del error mostrado durante el intento de recarga', upload_to=VaciosTickets.models.vacio_foto_upload, verbose_name='Foto: Error de Recarga')),
                ('motivo_falla', models.CharField(choices=[('error_red', 'Error de Red / Timeout'), ('caida_sistema', 'Caída del Sistema Central'), ('falla_software_maquina', 'Falla de Software en Máquina'), ('desconexion_brusca', 'Desconexión Brusca de Energía'), ('error_billetero', 'Error de Billetero / Ticket'), ('doble_cobro', 'Doble Cobro / Transacción Duplicada'), ('otro', 'Otro (ver explicación)')], help_text='Categoría del fallo que originó el vacío', max_length=50, verbose_name='Motivo de Falla')),
                ('explicacion_detallada', models.TextField(help_text='Descripción técnica completa de lo ocurrido', verbose_name='Explicación Detallada')),
                ('estado_operativo', models.CharField(choices=[('pendiente_autorizacion', 'Pendiente Autorización'), ('autorizado_carga', 'Autorizado para Carga'), ('carga_realizada', 'Carga Realizada')], default='autorizado_carga', help_text='Refleja si el ticket ha sido autorizado para proceder con la recarga', max_length=30, verbose_name='Estado Operativo')),
                ('estado_auditoria', models.CharField(choices=[('pendiente_revision', 'Pendiente de Revisión'), ('auditado_aprobado', 'Auditado / Aprobado'), ('rechazado_investigacion', 'Rechazado / En Investigación')], default='pendiente_revision', help_text='Veredicto del gerente sobre la legitimidad del vacío. Siempre inicia en "Pendiente de Revisión"', max_length=30, verbose_name='Estado de Auditoría')),
                ('casino', models.ForeignKey(help_text='Casino donde ocurrió el vacío', on_delete=django.db.models.deletion.PROTECT, related_name='tickets_vacios', to='Casinos.casino', verbose_name='Casino')),
                ('gerente_auditor', models.ForeignKey(blank=True, help_text='Gerente o Admin que emitió el veredicto de auditoría', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_vacios_auditados', to=settings.AUTH_USER_MODEL, verbose_name='Gerente Auditor')),
                ('maquina', models.ForeignKey(help_text='Máquina afectada', on_delete=django.db.models.deletion.PROTECT, related_name='tickets_vacios', to='Maquinas.maquina', verbose_name='Máquina')),
                ('tecnico_creador', models.ForeignKey(help_text='Técnico que abrió el ticket de vacío', on_delete=django.db.models.deletion.PROTECT, related_name='tickets_vacios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Creador')),
            ],
            options={
                'verbose_name': 'Ticket de Vacío',
                'verbose_name_plural': 'Tickets de Vacíos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
